### PR TITLE
Fixed issue where name was used instead of namespace in instructions 

### LINKED ISSUE #206: [Registry]: opentofu/aws/latest
### Feedback

Potential documentation issue on: https://search.opentofu.org/provider/opentofu/aws/latest

## How to use this provider
```hcl
terraform {
  required_providers {
    opentofu = {
      source = "opentofu/aws"
      version = "v5.65.0" 
    }
  }
}

provider "aws" {
  # Configuration options
}
```

``` bash
tofu init --upgrade

Initializing the backend...
╷
│ Error: Invalid version constraint
│
│   on providers.tf line 3, in terraform:
│    3:     opentofu = {
│    4:       source  = "opentofu/aws"
│    5:       version = "v5.65.0"
│    6:     }
│
│ Incorrect version constraint syntax: a "v" prefix should not be used.
╵
````

## It will also try to Install both opentofu/aws and hashicorp/aws
```bash
 tofu init --upgrade

Initializing the backend...

Initializing provider plugins...
- Finding opentofu/aws versions matching "<= 5.65.0"...
- Finding latest version of hashicorp/aws...
- Using previously-installed opentofu/aws v5.65.0
- Using previously-installed hashicorp/aws v5.66.0

╷
│ Warning: Potential provider misconfiguration
│
│ OpenTofu has detected multiple providers of type aws (opentofu/aws, hashicorp/aws) which may be a misconfiguration.
│
│ If this is intentional you can ignore this warning
╵
```

## Fix
```hcl
terraform {
  required_providers {
    aws= { # <-- change to "aws"
      source = "opentofu/aws" 
      version = "5.65.0" #<-- removed the "v"
    }
  }
}

provider "aws" {
  # Configuration options
}
```
```bash
tofu init --upgrade

Initializing the backend...

Initializing provider plugins...
- Finding opentofu/aws versions matching "<= 5.65.0"...
- Using previously-installed opentofu/aws v5.65.0

OpenTofu has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

OpenTofu has been successfully initialized!
```

### PR DESCRIPTION
**Pull request by Yantrio**
Fixes #206 

Signed-off-by: James Humphries <james@james-humphries.co.uk>## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] My contribution is compatible with the MPL-2.0 license and I have provided a DCO sign-off on all my commits.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.

### CODE REVIEW

File: frontend/src/routes/Provider/components/InstructionSidebarBlock.tsx [hunk 1]
```diff
@@ -26,11 +26,15 @@ export function ProviderInstructionSidebarBlock() {
...
+  // e.g. v0.1.0 -> 0.1.0
+  const versionConstraint = version.replace(/^v/, "");
+
   const instruction = `terraform {
   required_providers {
-    ${data.addr.namespace} = {
+    ${data.addr.name} = {
       source = "${data.addr.namespace}/${data.addr.name}"
-      version = "${version}"
+      version = "${versionConstraint}"
```
Comment (damianstasik) [inline frontend/src/routes/Provider/components/InstructionSidebarBlock.tsx:37]: We'll need to do the same for modules.

**Review by damianstasik — APPROVED** [review]
